# Generated by Django 2.2.6 on 2019-11-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191112_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dala',
        ),
    ]
